### ISSUE TITLE
Is there any way to use this without installing RPM or package ? 

### ISSUE THREAD

**Issue by AvinashDalvi89** [yeslogic/prince-php-wrapper#16]
I am looking for option which can used Price binary file without installing into linux system ? Like just adding into code base and using directly?

**Comment by wezm** [comment]
The [Prince contructor](https://yeslogic.github.io/prince-php-wrapper/current/classes/Prince-Prince.html#method___construct) takes the path to prince as an argument so if you extracted an appropriate [Prince download](https://www.princexml.com/download/15/) to your code base it could work as you describe—assume you local machine and the server are running the same OS and CPU architecture.

**Comment by AvinashDalvi89** [comment]
I have same OS because running using Docker image which used in other environment also. I tried using this binary file directly but throwing error.

**Comment by wezm** [comment]
> I tried using this binary file directly but throwing error.

If you would like more assistance you’ll need to provide more details/a copy of the error.

**Comment by AvinashDalvi89** [comment]
<img width="1020" alt="Screenshot 2024-01-30 at 12 05 00 PM" src="https://github.com/yeslogic/prince-php-wrapper/assets/3996105/07ac4a65-4411-4038-badd-f0649a8c27cd">
And output of this 
 
```
$result = $prince->convert_string_to_passthru($html);
 var_dump($result);exit;
```
 
is getting `bool(false)`

in error_log not much details about exact error.

**Comment by wezm** [comment]
`convert_string_to_passthru` (or better yet [`convertStringToPassthru`](https://yeslogic.github.io/prince-php-wrapper/current/classes/Prince-Prince.html#method_convert_string_to_passthru) as `convert_string_to_passthru` is deprecated) takes a second argument that will have errors and warnings written to it. I suggest supplying a value to that argument. Something like the (untested) code below:

```php
$msgs = array();
$success = $prince->convertStringToPassthru($html, $msgs);
if (!$success) {
    var_dump($msgs);
}
```

**Comment by AvinashDalvi89** [comment]
`array(8) { [0]=> array(3) { [0]=> string(3) "wrn" [1]=> string(11) "-:style:124" [2]=> string(36) "missing value for property 'display'" } [1]=> array(3) { [0]=> string(3) "wrn" [1]=> string(11) "-:style:140" [2]=> string(49) "parse error in value of property 'display' at '%'" } [2]=> array(3) { [0]=> string(3) "wrn" [1]=> string(11) "-:style:143" [2]=> string(49) "parse error in value of property 'display' at '%'" } [3]=> array(3) { [0]=> string(3) "wrn" [1]=> string(1) "-" [2]=> string(30) "unsupported properties: quotes" } [4]=> array(3) { [0]=> string(3) "wrn" [1]=> string(0) "" [2]=> string(76) "Ensure fonts are available on the system or load them via a @font-face rule." } [5]=> array(3) { [0]=> string(3) "wrn" [1]=> string(0) "" [2]=> string(25) "For more information see:" } [6]=> array(3) { [0]=> string(3) "wrn" [1]=> string(0) "" [2]=> string(67) "https://www.princexml.com/doc/help-install/#missing-glyphs-or-fonts" } [7]=> array(3) { [0]=> string(3) "err" [1]=> string(0) "" [2]=> string(35) "Unable to find any available fonts." } }`

**Comment by wezm** [comment]
Right you have no fonts available. You will need to use @font-face rules to load fonts or install fonts on the host system. See the link in the error message.

**Comment by AvinashDalvi89** [comment]
Is there way to disable this font ? like don't wish to use fonts setting ? I tried but no luck. I would like to install anything inside OS level. Can this be done inside folder itself like using binary file ? 
```
 $prince->setNoArtificialFonts(false);
        $prince->setEmbedFonts(false);
```

**Comment by AvinashDalvi89** [comment]
I added under template which I am using to populate HTML content but still same issue. I checked HTML content font-face is applying there. But for prince getting same error. What path prince expect ?

**Comment by adrianwong** [comment]
Have you specified the correct path to your fonts relative to where the `@font-face` rules have been declared?

Otherwise, please provide us with more information (the `@font-face` rules you've declared are a good start).

**Comment by AvinashDalvi89** [comment]
Gave path where font file is there. In template able to see that.

**Comment by adrianwong** [comment]
On my Linux machine, I'm able to generate a minimal example that finds a specified font just fine. Honestly, I'd be surprised if this is an undiscovered issue with Prince's implementation, considering how common this use-case is.

Closing, as there is nothing further we're able to do without further input from you. Feel free to reopen if you do decide to provide us with some code.
