### ISSUE TITLE
Is there any way to remove watermark logo of "P" 

### ISSUE THREAD

**Issue by AvinashDalvi89** [yeslogic/prince-php-wrapper#17]
Need to remove watermark logo. is it only allow in license ? 
![Screenshot 2024-02-22 at 11 30 09 AM](https://github.com/yeslogic/prince-php-wrapper/assets/3996105/7352a124-313b-4ee2-b5a4-0a17ae5c330a)

**Comment by wezm** [comment]
> is it only allow in license ?

Yes. 

![image](https://github.com/yeslogic/prince-php-wrapper/assets/21787/2326dbf4-bbe0-4f82-9da0-28aa45fe83f0)

https://www.princexml.com/purchase/license_faq/

**Comment by AvinashDalvi89** [comment]
we do have license.dat file under folder but still coming this watermark ? is there any step missing after upgrading ?

**Comment by AvinashDalvi89** [comment]
Getting this error :prince: /usr/lib/prince/license/license.dat: warning: inapplicable license for this version

**Comment by adrianwong** [comment]
Please ask license-related questions on the [Prince forum](https://www.princexml.com/forum/). This tracker should be reserved for issues specific to the PHP wrapper.
